import os

USER_DIR = os.environ['HOME']
DOCUMENTS_DIR = USER_DIR
ATRAIN_DIR = USER_DIR
MODELS_DIR = USER_DIR
TRANSCRIPT_DIR = USER_DIR
METADATA_FILENAME = "metadata.txt"
LOG_FILENAME = "log.txt"
TIMESTAMP_FORMAT = "%Y-%m-%d %H-%M-%S"
SAMPLING_RATE = 16000
REQUIRED_MODELS = []
